year            = 2006
data_loader     = "load_and_prepare_e2006"
data_file       = "data/02489/1_02489.sav"
max_candidates  = 6
m_values_range  = [2, 3, 4, 5, 6]

n_bootstrap     = 3
n_alternatives  = 6
force_include   = []
rng_seed        = 42

candidates = [
  "Lula", "Geraldo_Alckmin", "Heloísa_Helena",
  "Cristóvam_Buarque", "Aécio_Neves", "José_Serra"
]

demographics = ["Sex", "Ideology", "PT", "Age", "Education", "Income"]

forced_scenarios = [
  { name = "no_forcing",   candidates = [] },
  { name = "lula_alckmin", candidates = ["Lula", "Geraldo_Alckmin"] }
]

